--------------------------------------------------------
-- Archivo creado  - jueves-diciembre-27-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CM_ACCT_ORD_STG
--------------------------------------------------------

-- Version inicial

  CREATE TABLE "INTEGRADOR"."CM_ACCT_ORD_STG" 
   (	"CM_STG_UP_ID" CHAR(10 BYTE), 
	"ACCT_ID" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0049706
--------------------------------------------------------

  CREATE UNIQUE INDEX "INTEGRADOR"."SYS_C0049706" ON "INTEGRADOR"."CM_ACCT_ORD_STG" ("CM_STG_UP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0049707
--------------------------------------------------------

  CREATE UNIQUE INDEX "INTEGRADOR"."SYS_C0049707" ON "INTEGRADOR"."CM_ACCT_ORD_STG" ("ACCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CM_ACCT_ORD_STG
--------------------------------------------------------

  ALTER TABLE "INTEGRADOR"."CM_ACCT_ORD_STG" MODIFY ("ACCT_ID" NOT NULL ENABLE);
  ALTER TABLE "INTEGRADOR"."CM_ACCT_ORD_STG" ADD PRIMARY KEY ("CM_STG_UP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "INTEGRADOR"."CM_ACCT_ORD_STG" ADD UNIQUE ("ACCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
